name: Build CI
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest] # ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Generate
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 16 2019" -A x64 ..
        cd ..
    - name: Build
      run: |
        cmake --build build/ --parallel --config Release
